[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { workspace = true }
diesel = { workspace = true }
jsonwebtoken = { workspace = true }
serde = { workspace = true }
